import React, { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import api from '../services/api';

const ReceiptPreview = () => {
    const { id } = useParams();
    const navigate = useNavigate();
    const [receipt, setReceipt] = useState(null);
    const [error, setError] = useState(null);

    useEffect(() => {
        // Fetch receipt data from backend with auth headers
        api.get(`/sales/${id}`)
            .then(data => setReceipt(data))
            .catch(err => {
                console.error('Error fetching receipt:', err);
                setError(err.message || 'Unable to load receipt');
            });
    }, [id]);

    if (error) return <div className="p-8 text-red-600">{error}</div>;
    if (!receipt) return <div className="p-8">Loading Receipt...</div>;

    const handlePrint = () => window.print();
    const handleDownload = () => {
        const escapeXml = (value) => String(value)
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/"/g, '&quot;')
            .replace(/'/g, '&apos;');

        const title = '*** SMS RECEIPT ***';
        const dateText = new Date(receipt.date || receipt.created_at).toLocaleString('en-GB', { hour12: false });
        const customerText = receipt.customer_name || 'Valued Customer';
        const generatedByText = receipt.cashier_name || 'Unknown';
        const lines = [
            title,
            `Receipt #: ${receipt.id || receipt.saleId}`,
            `Date: ${dateText}`,
            `Customer: ${customerText}`,
            `Generated by: ${generatedByText}`,
            '----------------------------------------',
            'Item                        Qty   Total',
            '----------------------------------------',
            ...((receipt.items || []).map((item) => {
                const name = String(item.product_name || item.name || 'Item').slice(0, 24);
                const qty = String(item.quantity || 0);
                const total = `GHS ${Number(item.line_total || ((item.quantity || 0) * Number(item.unit_price || item.price || 0))).toFixed(2)}`;
                return `${name.padEnd(24)} ${qty.padStart(3)} ${total.padStart(11)}`;
            })),
            '----------------------------------------',
            `GRAND TOTAL: GHS ${Number(receipt.total || receipt.total_amount).toFixed(2)}`,
            '----------------------------------------',
            'Thank you for your purchase!',
            'Visit again.'
        ];

        const svgWidth = 640;
        const lineHeight = 28;
        const padding = 24;
        const headerHeight = 120;
        const footerHeight = 80;
        const svgHeight = headerHeight + lines.length * lineHeight + footerHeight;

        const svgLines = lines.map((line, index) => {
            const y = headerHeight + index * lineHeight;
            const className = index === 0 ? 'title' : 'line';
            return `<text x="${padding}" y="${y}" class="${className}">${escapeXml(line)}</text>`;
        }).join('');

        const svg = `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="${svgWidth}" height="${svgHeight}" viewBox="0 0 ${svgWidth} ${svgHeight}">
    <style>
        .background { fill: #ffffff; }
        .title { font: 700 22px ui-monospace, Menlo, Monaco, Consolas, 'Courier New', monospace; fill: #111827; }
        .line { font: 16px ui-monospace, Menlo, Monaco, Consolas, 'Courier New', monospace; fill: #111827; }
        .small { font: 14px ui-monospace, Menlo, Monaco, Consolas, 'Courier New', monospace; fill: #4b5563; }
    </style>
    <rect width="100%" height="100%" rx="18" ry="18" class="background" />
    ${svgLines}
    <text x="${padding}" y="${svgHeight - 40}" class="small">This generated receipt is final and read-only.</text>
</svg>`;

        const blob = new Blob([svg], { type: 'image/svg+xml;charset=utf-8' });
        const url = URL.createObjectURL(blob);
        const image = new Image();

        image.onload = () => {
            const canvas = document.createElement('canvas');
            const scale = 2;
            canvas.width = svgWidth * scale;
            canvas.height = svgHeight * scale;
            const context = canvas.getContext('2d');
            context.scale(scale, scale);
            context.fillStyle = '#ffffff';
            context.fillRect(0, 0, svgWidth, svgHeight);
            context.drawImage(image, 0, 0);
            canvas.toBlob((pngBlob) => {
                if (!pngBlob) return;
                const pngUrl = URL.createObjectURL(pngBlob);
                const link = document.createElement('a');
                link.href = pngUrl;
                link.download = `receipt-${receipt.id || receipt.saleId}.png`;
                document.body.appendChild(link);
                link.click();
                document.body.removeChild(link);
                URL.revokeObjectURL(pngUrl);
                URL.revokeObjectURL(url);
            }, 'image/png');
        };

        image.onerror = () => {
            URL.revokeObjectURL(url);
            alert('Unable to generate receipt image.');
        };

        image.src = url;
    }

    return (
        <div className="receipt-page">
          <div className="receipt-ops" id="receipt-content">
            <div className="receipt-header text-center mb-4">
                <div className="receipt-title">*** SMS RECEIPT ***</div>
                <div className="receipt-meta">Receipt #: {receipt.id || receipt.saleId}</div>
                <div className="receipt-meta">Date: {new Date(receipt.date || receipt.created_at).toLocaleString('en-GB', { hour12: false })}</div>
                <div className="receipt-meta">Customer: {receipt.customer_name || 'Valued Customer'}</div>
            </div>

            <div className="receipt-details mb-4">
                <div>Generated by: {receipt.cashier_name || 'Unknown'}</div>
                <div className="text-sm text-gray-600 mt-2">This generated receipt is final and read-only.</div>
            </div>

            <div className="receipt-items mb-4">
                <div className="receipt-row receipt-row--header">
                    <span>Item</span>
                    <span>Qty</span>
                    <span className="receipt-total">Total</span>
                </div>
                {(receipt.items || []).map((item, index) => (
                    <div key={index} className="receipt-row">
                        <span>{String(item.product_name || item.name || 'Item').slice(0, 24)}</span>
                        <span>{item.quantity || 0}</span>
                        <span className="receipt-total">GHS {Number(item.line_total || ((item.quantity || 0) * Number(item.unit_price || item.price || 0))).toFixed(2)}</span>
                    </div>
                ))}
            </div>

            <div className="receipt-summary mb-6">
                <div className="receipt-summary-line">GRAND TOTAL: GHS {Number(receipt.total || receipt.total_amount).toFixed(2)}</div>
            </div>

            <div className="receipt-footer mb-4">
                <div>Thank you for shopping with us!</div>
                <div>Powered by SMS receipts.</div>
            </div>

            <div className="flex gap-4 no-print">
                <button 
                    onClick={handlePrint}
                    className="flex-1 bg-blue-600 text-white py-2 rounded hover:bg-blue-700 transition"
                >
                    Print Receipt
                </button>
                <button 
                    className="flex-1 bg-gray-200 text-gray-800 py-2 rounded hover:bg-gray-300 transition"
                    onClick={handleDownload}
                >
                    Download PNG
                </button>
                <button 
                    onClick={() => navigate('/sales')}
                    className="flex-1 border border-gray-300 py-2 rounded hover:bg-gray-50 transition"
                >
                    Back to Sales
                </button>
            </div>
          </div>
        </div>
    );
};

export default ReceiptPreview;